find_path(
	OPENNI2_INCLUDE_DIR 
	NAMES "OpenNI.h"
	PATHS $ENV{OPENNI2_INCLUDE}
	)
find_library(
	OPENNI2_LIBS 
	NAMES OpenNI2
	PATHS $ENV{OPENNI2_REDIST}
	)

set(OPENNI2_INCLUDE_DIR ${OPENNI2_INCLUDE_DIR})
set(OPENNI2_LIBS ${OPENNI2_LIBS})

if(OPENNI2_INCLUDE_DIR)
	message("OPENNI2_INCLUDE_DIR found at " ${OPENNI2_INCLUDE_DIR} )
	set (OPENNI2_INCLUDE_DIR_FOUND TRUE)
	include_directories(${OPENNI2_INCLUDE_DIR})
endif(OPENNI2_INCLUDE_DIR)

if(OPENNI2_LIBS)
	message("OPENNI2_LIBS found at " ${OPENNI2_LIBS} )
	set (OPENNI2_LIBS_FOUND TRUE)
	link_directories(${OPENNI2_LIBS})
endif(OPENNI2_LIBS)
